### ISSUE TITLE
配置差不多

### ISSUE THREAD

**Issue by zhumao520** [weiyien/Hackintosh_GIGABYTE_Z-490_I5-10400#1]
我也是用的这个 ufi 也是核显没打开 显卡也不一样 开机 偶尔开机黑屏

**Comment by weiyien** [comment]
玩黑苹果讲配置差不多就很迷.

**Comment by zhumao520** [comment]
> 玩黑苹果讲配置差不多就很迷.

我是真正的小白白

**Comment by weiyien** [comment]
其实我也只了解一点点.着急用就去找了tb..

**Comment by weiyien** [comment]
> > 玩黑苹果讲配置差不多就很迷.
> 
> 我是真正的小白白

建议找配置相同的efi.   实在不行tb处理.

**Comment by zhumao520** [comment]
> > > 玩黑苹果讲配置差不多就很迷.
> > 
> > 
> > 我是真正的小白白
> 
> 建议找配置相同的efi. 实在不行tb处理.
兄弟可以教教我不 qq:66694576
